### ISSUE TITLE
解码时候为什么用贪心搜索？而不是topk topp

### ISSUE THREAD

**Issue by nieallen** [Miraclemarvel55/ChatGLM-RLHF#1]
作者你好，疑问如题

**Comment by Miraclemarvel55** [comment]
贪心搜索可以拿到当前最大概率的词汇，再通过强化学习来提升或者降低它的概率，贪心我认为会收敛的更快些，因为每次都对最高概率的那一个做改变。beam_search也是支持的。贪心只有一条结果省显存呀，哈哈。至于topk topp，贪心相当于top1了，这些采样方法都OK，重要的是拿到采样句子的每个token的log_prob。

**Comment by Miraclemarvel55** [comment]
问题已回答
