### ISSUE TITLE
大佬，问个low的问题，效果展示是执行哪个代码？优化后的模型需要保存吗

### ISSUE THREAD

**Issue by zxy333666** [Miraclemarvel55/ChatGLM-RLHF#2]

**Comment by Miraclemarvel55** [comment]
这个即可：python chatglm_rlhf.py 里面有一个qa_log变量保存了，每次回答同样问题的变化。保存与否看自己情况。
简单的问题也可以问一下群友能得到及时的回复。

**Comment by zxy333666** [comment]
好的，感谢大佬，保存下来了，也看到了效果

**Comment by GUORUIWANG** [comment]
> zxy333666

请教一下，大佬在哪里加载的模型，如何进行预测看效果的
